# Generated by Django 4.2.3 on 2023-07-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldetails', '0002_remove_course_students_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
