# Generated by Django 4.2.3 on 2023-07-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooldetails', '0003_alter_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=None),
        ),
    ]
